### ISSUE TITLE
segmenter warning log

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#101]
it would be nice for the segmenter warning log to have more info to locate the form, such as line number or id

**Comment by nataliacp** [comment]
and another idea. in the cases where you do the automatic conversions from say tie bar t s to t tiebar s, it is done only at the level of the segments, right? It would be nice to warn the user, so they go and correct the forms.csv as well.

**Comment by PaprikaSteiger** [comment]
I'll add the id of the form to the warning. New warning will be:
"Unknown sound encountered in {form_id} in {formstring:}"

**Comment by nataliacp** [comment]
it would be better to be explicit about the unknown sound too.
Unknown sound X ...

**Comment by nataliacp** [comment]
more ideas here: is it easy to have a kind of report that says: In language blabla you had XX instances of this character (which is not IPA) that was interpreted as this character (in IPA) for the segments. I think this would help people catch inconsistencies in their unified forms.

**Comment by PaprikaSteiger** [comment]
@nataliacp I hope this is more or less the kind of report you wanted. Currently the output when calling segment_using_clts.py looks like this.
The warnings are printed and in the end you get a table, listing all the languages and the different errors/replacements that were found. This is the report for the maweti-test set, so other warnings like 'unknown pre-aspiration' are not present.
Do you have a erroneous dataset with the cases of wrong aspiration, nasalization etc.?
```
python -m lexedata.enrich.segment_using_clts --metadata <...> --overwrite
WARNING:root:In form ache_one (line 1): Unknown sound ' encountered in e.ta.'kɾã
WARNING:root:In form ache_two (line 5): Unknown sound ' encountered in mĩ.'ɾõ1
WARNING:root:In form ache_three (line 9): Unknown sound ' encountered in bɾe.'wi pɨ.'ʧa
WARNING:root:In form ache_three (line 9): Unknown sound ' encountered in bɾe.'wi pɨ.'ʧa
WARNING:root:In form ache_four (line 12): Unknown sound ' encountered in gwɨ.'ɾa pɨ.'ʧa
WARNING:root:In form ache_four (line 12): Unknown sound ' encountered in gwɨ.'ɾa pɨ.'ʧa
WARNING:root:In form ache_four_1 (line 15): Unknown sound ' encountered in i.ɾõ.'ndɨ

| LanguageID   | Sound   |   Occurrences | Comment       |
|--------------+---------+---------------+---------------|
| ache         | .       |             5 | pre-replace   |
| ache         | '       |             7 | unknown sound |
```
Now you get one table containing all languages. Another possibility would be to print one table per language. So it wouldn't have the LanguageID column. What is better for you, Natalia?

**Comment by PaprikaSteiger** [comment]
I also added a new argument called 'replace-form', if activated the pre-replacements (e.g. "͡tʃ" -> "t͡ʃ") are also applied to the \#form column in \#FormTable
