### ISSUE TITLE
plus signs for morpheme boundaries are problematic in the beginning of forms in google sheets

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#104]
bow (n.)12.2 in Baniwa is an example of this. it becomes an error in googlesheets (probably thinks it is a formula of sorts)

**Comment by Anaphory** [comment]
@nataliacp I think we have given up on + as morpheme boundary everywhere, so we should not have this issue any more?

**Comment by Anaphory** [comment]
The option to have them keeps popping up, but I shall add warnings to not do that wherever I find them.
