### ISSUE TITLE
phylogenetics exporter needs to take into account primary concept

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#110]
at least for cases where cross-concept cognate sets are present. But it may be useful also to verify root-concept sets as well.

**Comment by Anaphory** [comment]
I have given the phylogenetics exporter an overhaul.
Root-Concept sets can be configured using a list of concepts (in this case, concepts to be excluded, but we can discuss the details) fed to the command line. Writing a generic filter function inside the phylogenetics exporter command line is not practical, so I think that's okay.

For core concepts in root-presence coding, it works like this:

> First, generate some helpers: For every language, which roots in contains; for each cognateset, which concepts it is related to; and the list of all possible roots. I also know the extent of the lexicon for each language.
> Then, for each language and each root, check:
> - If the root is present, it's present.
> - If the root is absent, consider all the concepts that are at all associated with the root.
>   filter these down to some important ones: If any of the important concepts are attested in the lexicon of the language, even if they are only attested by an NA form, take this particular root as absent, otherewise we take it as unknown.

Does this make sense? How should we make the ‘importance’ restriction?
Find the central concept, and if it is a core concept, take it and all other core concepts that are CLICS-adjacent; if it's not a core concept, no concept is important, maybe?

**Comment by Anaphory** [comment]
@nataliacp This is what we have (conceptually) at the moment, but we should discuss how that interacts with filters.
Should, for the root-presence coding, the ‘concept list’ be interpreted as the list of ‘important concepts’ (named ‘core concepts’ above)?

NB: I think core concept is good here, and I think the central concept among all of those which a cognate set relates to could be the central concept, but I'm happy to take other terms if we think of any.

**Comment by Anaphory** [comment]
The IMPORTANCE restriction would be made explicity by specifiying a `--concept-list` on the CLI, which would usually be generated by filtering the concepts table to PRIMARY concepts.

**Comment by Anaphory** [comment]
All sorted, and partially tested.
