### ISSUE TITLE
￼ Test both #parameterReference with a separator and without a separator.

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/lexedata#116]
We have some tests for this in places already, but we should explicitly test that every one of our scripts works with single-concept forms and with multi-concept forms, and add understandable error messages where a script doesn't.

This is one of the cases of #63

**Comment by Anaphory** [comment]
@PaprikaSteiger Could you have a look to see where our tests assume that `dataset["FormTable", "parameterReference"].separator is None` and add tests for the other case where the separator is set?

**Comment by PaprikaSteiger** [comment]
For the moment, I just checked all scripts and tests if they contain .separator. Could you have a quick look and tell me which scripts I should extend with .separator.

Test files that contain .separator in some way:
- test_additional_importer.py (1 test with .separator = None)
-  test_excel_conversion.py (1 test with .separator = ",")
- test_form_matcher.py (1 test with .separator = ";")

Scripts that mention .separator in some way:
-  importer/cognates.py
- importer/edictor.py
-  excel_long_format.py
- excel_matrix.py
-  exporter/cognates.py
-  exporter/cognates.py
-  phylogenetics.py
-  add_judgement_table.py
-  add_segments.py (separator for segment column)
-  coverage.py
- extended_cldf_validate.py

scripts possibly in need of .separator:
-  edit/add_central_concepts.py
-  edit/add_concepticon.py

**Comment by Anaphory** [comment]
I just noticed when testing the Matrix exporter that it seems we have a good mix of separators in the test data sets already. So maybe we can close this issue.
