### ISSUE TITLE
Use foreign keys instead of references

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/lexedata#128]
From #81:
> Essentially, all the scripts that read some table into a dictionary indexed by #id and then glue that to some other table based on #xxxReference need to be changed to instead do the gluing based on the foreign key relationship.
>
> @PaprikaSteiger how should we do this? Step by step as we go through the programs, or in one concentrated effort?

I have made a generic function for caching available in `lexedata.util` and implemented a first use case in the extended validation script. We should take it from there.

**Comment by Anaphory** [comment]
For example, `report.homophones` has:

    c_id = dataset["ParameterTable", "id"].name
    c_concepticon = dataset["ParameterTable", "concepticonReference"].name
    concepticon = {}
    for concept in dataset["ParameterTable"]:
        concepticon[concept[c_id]] = concept[c_concepticon]

The mapping should not happen using dataset["ParameterTable", "id"].name, but instead using the referenced column of the foreign key associated with FormTable's parameterReference.

Maybe we want to manipulate one of our test datasets to have FormTable reference Names, not IDs, of ParameterTable and see which tests fail, to see what needs fixing.

**Comment by Anaphory** [comment]
I should note that I haven't seen these non-ID mappings in the wild, so the danger from implementing things the naïve way seems to not be too high.

**Comment by Anaphory** [comment]
The simplify_ids scripts show examples for how to get foreign keys and manipulate them.

**Comment by PaprikaSteiger** [comment]
@Anaphory Just to make sure: this style `dataset.column_names.cognatesets.parameterReference` should also be replaced by the style provided in simplify_ids, right?

**Comment by PaprikaSteiger** [comment]
> For example, `report.homophones` has:
> 
> ```
> c_id = dataset["ParameterTable", "id"].name
> c_concepticon = dataset["ParameterTable", "concepticonReference"].name
> concepticon = {}
> for concept in dataset["ParameterTable"]:
>     concepticon[concept[c_id]] = concept[c_concepticon]
> ```
> 
> The mapping should not happen using dataset["ParameterTable", "id"].name, but instead using the referenced column of the foreign key associated with FormTable's parameterReference.
> 
> Maybe we want to manipulate one of our test datasets to have FormTable reference Names, not IDs, of ParameterTable and see which tests fail, to see what needs fixing.

And after all this time, I've already started forgetting the details. Thus, you want `c_id = dataset["ParameterTable", "id"].name` replaced by `c_id = "get the foreign key connecting FormTable to ParameterTable`

**Comment by Anaphory** [comment]
We have decided to check that foreign key relationships are sensible (target table as expected, target column is ID) in extended validate.
