### ISSUE TITLE
Tell the user more about where they are and how much time is left for that step

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/lexedata#133]
Make deliberate and extensive use of `logger.info` and `cli.tq`, because if someone really doesn't want that, they can use `-q` (only implemented for a few scripts so far, but we can improve) to silence the output of both.

**Comment by PaprikaSteiger** [comment]
Files to check for @Anaphory 
- [ ] edit.detect_conates.py
- [ ] exporter.edictor.py
- [ ] [ ] exporter.phylogenetics.py

What about the report scripts?
