### ISSUE TITLE
error when running the long format importer

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#158]
I was trying to import a new dataset with the Arawak format and I got the following error. 

``` natalia:oto-pamean$python -m lexedata.importer.fromexcel --metadata Wordlist-metadata.json Otomanguean.xlsx 
/Users/natalia/.local/lib/python3.8/site-packages/csvw/datatypes.py:67: FutureWarning: Possible nested set at position 12
  return {'regex': re.compile(
Traceback (most recent call last):
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/natalia/Documents/lexedata/src/lexedata/importer/fromexcel.py", line 839, in <module>
    args.metadata, args.lexicon, args.cogsets, args.status_update, logger=logger
AttributeError: 'Namespace' object has no attribute 'lexicon'```

**Comment by Anaphory** [comment]
I'm fixing this, but:

@nataliacp The Arawak format, the long list of wordlists, should be `lexedata.importer.excelsinglewordlist`, but what you show here only happens when `fromexcel` is called, did you use the Maweti-Guaraní-importer?

**Comment by nataliacp** [comment]
I indeed tried with excelsingle wordlist first and it did the same thing
(or at least so I remember, it looked similar). Then I thought that I had
it wrong in my head and tried the other way. I was confused because
afterwards I thought that the single wordlist is only to add languages.
