### ISSUE TITLE
Guessing scripts should update status or warn

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/lexedata#161]
Scripts that add stuff based on heuristics (central_concepts, concepticon) must set a status that contains the string “auto” or warn that they couldn't get acces to a status column

**Comment by Anaphory** [comment]
- [ ] add_central_concepts.py
 - [ ] add_concepticon.py
 - [X] add_metadata.py
 - [ ] add_table.py (maybe?)

**Comment by PaprikaSteiger** [comment]
@Gereon So all the scripts should just write 'auto' to the status column? So far we have 'automatic Concepticon link', so I would follow that style, e.g. 'automatic central concepts' etc.

**Comment by PaprikaSteiger** [comment]
And also, so far we call the `add_status_column function`, if a scripts writes to a status column but the dataset doesn't contain one so far...

**Comment by Anaphory** [comment]
>  So all the scripts should just write 'auto' to the status column? So far we have 'automatic Concepticon link', so I would follow that style, e.g. 'automatic central concepts' etc.

Yes, that's the pattern I thought. But for tests it's enough to check that `"auto" in status.lower()`, we don't want to be too restrictive in our tests.

**Comment by Anaphory** [comment]
> And also, so far we call the `add_status_column function`, if a scripts writes to a status column but the dataset doesn't contain one so far...

It could always be that someone doesn't want their dataset structure changed, so it must be possible to deactivate that. Somehow, I prefer warning the user and telling them to add a status column themselves, but then again `git checkout` is easy for me, so undoing a script that didn't run as I expected is no problem.

**Comment by PaprikaSteiger** [comment]
I added a status update to the mentioned scripts. However, I don't think it makes sense to add a status column with the add_table.py script as this script will only add an empty table.
