### ISSUE TITLE
comments on lexedata.edit.add_metadata

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#168]
I just ran this for the first time on a forms.csv from the Bantu project. 
Here are my observations (not necessarily problems and not urgent)
- i had columns named Form_ID and Concept_ID and it complained that it couldn't find ID and Parameter_ID. Easily fixable, but could it be a bit smarter at least for Concept (since the table is called concepts.csv)?
- I had a Variants column (with a ~ separator) and it was recognized as a string with "format": "\\s*(~|)\\s*[[/(].*[]/)]\\s*" and a comma separator (even though there is no comma present in this column). Also, it throws a bunch of warnings for ivalid lexical value for string. There is nothing wrong in these strings from my perspective, they have normal IPA characters (I don't know about their encoding though)
- I had a Plural column which similarly had IPA forms in it and it was simply put as a string column, no warnings. Same with Translation column. So, I am puzzled that the variant column created such a fuss.

**Comment by Anaphory** [comment]
- [ ] Yes, Concept_ID sounds like a synonym we should recognize.
 - The idea of the Variants column is that it is a comma-separated list of variants. Each variant can, but doesn't have to, start with a `~` (we used that in MG: Some forms were explicity given by the sources as variants, separated by “~”, other forms were just listed without marking them as variants, and we put them in the variants column without `~`. Afterwards comes a form, with brackets to make clear whether it's an orthographic, phonemic or phonetic variant. If that's not the shape of your Variants column, we can come up with something else – either for the data set you are working with or for the default, to be discussed. There's no problem if you want to change it to a string column with `~` as separator, until we start writing tools that use variants to inform some decisions.
   - [ ] I don't know why the angular brackets for orthographic variants don't appear in there, though.
 - Plural isn't something we recognise as special, so you may put any strings in there.
