### ISSUE TITLE
Reconfigure report/coverage.py

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/lexedata#169]
- [x] Minimum Coverage should be a percentage and called --min-percentage
- [x] --languages-only may be not necessary?
- [x] There should be some consideration of primary concepts, see #170 
- [x] only --metadata. Don't allow forms. If you get a forms.csv, point to `add_metadata`.
- [ ] --missing can go, but we need to check our logic to see how we actually represent missing forms (i.e. row not present, row with empty form, row with form "-") - The report should not count rows with empty forms, and list both the total including "-" and the total excluding "-".
- [x] Coverage should be output as both a number of (primary) concepts and as a percentage
- [x] Activatable by switch (default False): Show separate report for Concepts, by the number of languages that attest them
- [ ] There may be a (command line? function?) with a confusing name, in a place that used to be Line 87 at some point…
- [x] use ForeignKeys to find the reference concepts, instead of assuming ParameterTable.id

**Comment by PaprikaSteiger** [comment]
@Anaphory I think we should discuss the remaining points at our next meeting.
