### ISSUE TITLE
comments on lexedata.exporter.cognates test with Bantu

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#175]
I finally managed to get a cognates.xlsx file from the Bantu dataset. Here are the problems I ran into:
- [ ] after the importation forms.csv had a bunch of ? forms as well as ? cognateset_IDs. I deleted them by hand. 
- [x] my first attempt to export a cognate file gave a cognateset keyerror, so I added trivial cognateset.csv and cognates.csv tables. 
- [x] Then I got a comment keyerror and a segments keyerror (presumably because my trivial .csvs didn't have such columns). I added empty columns of this sort, and then it worked.
- [ ] I am not sure how to fix this, but it seems a bit weird to me to require all these empty columns and trivial tables. 
- [ ] Also, these key error errors are relatively cryptic.

**Comment by PaprikaSteiger** [comment]
@nataliacp Hey Natalia, could you provide the data you used, when you're back from your vacations?
