### ISSUE TITLE
segmenter errors with Bantu

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#176]
the Bantu dataset creates an impressive list of errors when the segmenter is run. Some of the symbols seem ok to me, but probably the encoding is crazy? 
[BantuErrors.txt](https://github.com/Anaphory/lexedata/files/6649624/BantuErrors.txt)

**Comment by PaprikaSteiger** [comment]
UUps, I haven't seen this issue. I'll take care of it (:

**Comment by PaprikaSteiger** [comment]
@nataliacp I had a look at the error messages. So far I couldn't see an error that shouldn't happen.
Could you maybe tell me which sounds you expected not to throw an error?

**Comment by Anaphory** [comment]
It will probably cut down on the warnings a lot if you replace all the wrong stress marks (`'`, `ʼ`) with correct stress marks.
Bost of the other issues are diacritics that don't make sense to a strict IPA reader.
