### ISSUE TITLE
Coverage report (or similar) should also tell how many concepts have been *cognate coded*

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/lexedata#199]

**Comment by PaprikaSteiger** [comment]
Check the forms referencing a concept, then  count how many of those forms appear in the cognate table.

**Comment by PaprikaSteiger** [comment]
Also undo this foreign key style:

    # get the foreign keys pointing to the required tables
    foreign_key_parameter = ""
    for foreign_key in dataset["FormTable"].tableSchema.foreignKeys:
        if foreign_key.reference.resource == dataset["ParameterTable"].url:
            foreign_key_parameter = foreign_key.columnReference[0]

**Comment by Anaphory** [comment]
It is now done using the `--coded` switch.
