### ISSUE TITLE
help of importer.interleaved seems outdated

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#209]
Currently the command description reads: 

> Import some Bantu data This script is a very rough sketch for importing yet
> another shape of data. Here, every even column contains cells with forms (some
> cells containing multiple forms), while the odd columns contain the associated
> cognate codes (generally in the same order).

I  think it is not that rough any more, no? and of course it shouldn't say bantu! I can modify it, if you confirm!

**Comment by Anaphory** [comment]
Please do!

**Comment by nataliacp** [comment]
I updated the description. However, I think there are some optional arguments missing: 

- [ ] there should be a way that the separator is declared for the forms and for the cognate codes
- [ ] even though the forms can have more info to them, none of them is separable at the moment (as far as I understand). I can imagine reusing the matrix importer to do this, but I think it is a lot of work and not a priority. However, I think that warning that at the moment only forms are separable and any other information has to be separated by hand is useful. I can add this if you confirm that my understanding is correct. 
- [ ] there should be something about empty cells or question marks ideally. If it is a file that has been already used for phylogenetics, it would probably have ?. Then they shouldn't be treated as forms (which seems to have been the case in the past, but no longer is!!!). However, it should be configurable. an optional argument of forms to ignore (such as ?, NA or blanks) may be a solution. 
- right now a comment column appears. I assume this is to be populated by comments on the excel cells. 
- finally, in order to test further, I have stripped the Bantu dataset of pretty much everything else that existed in the cells (translations, sources, variants) because I would have to treat them by hand. Do you see a problem with this?

**Comment by Anaphory** [comment]
- Currently, both comma and semicolon are accepted as separators. We could of course expose this to be set by the user, but do you think it's really useful? Have you seen other separators?
 - Yes, currently everything separated by comma or semicolon is considered a separate form, and if there is noise in that “form” (eg. brackets in there for comments or variants), that is just added to the Form column and needs to be split later. Do you imagine the warning only if we detect nonsense (eg. brackets), or in any case in the description or immediate output of the program?
 - Cells with "?" are currently not imported as forms, which should lead to a "?" in the phylogenetics export. We could add them as blank (i.e. NA) forms depending on a switch, if you think that is wise.
 - [ ] A default data set has a comment column. We could indeed read it from Excel comments, but should we?
 - No problem with stripping data.

**Comment by nataliacp** [comment]
the comment field is created by default, nothing goes in there.

**Comment by nataliacp** [comment]
I will put the "warning" in the description and I put it in the manual as well. Sorry, I forgot warning is special talk, haha!

**Comment by nataliacp** [comment]
regarding question marks, if somebody has inconsistent question marks right now (i.e. some blank cells when they should be question marks), then they would all be ignored, right?
if yes, then I don't think we need to do anything. I will just say it in the manual
