### ISSUE TITLE
importer.excel_long_format optional arguments

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#210]
In the help, the optional arguments for this command seem to have hyphens separating words rather than underscores. In how many places does this need to be changed? Can I do it?

> 
>   --concept-name CONCEPT_NAME
>                         Column to interpret as concept names Default: assume
>                         the #parameterReference column, usually named
>                         'Concept_ID' or similar, matches the IDs of the
>                         concept. Use this switch if you have concept Names in
>                         the wordlist instead.
>   --sheet SHEET         Sheet to parse. Use multiple --sheet=Name arguments
>                         for multiple sheets. (default: all)
>   --match-form [MATCH_FORM [MATCH_FORM ...]]
>                         Columns to match forms by
>   --ignore-superfluous-excel-columns, -s
>                         Ignore columns in the Excel table which are not in the
>                         dataset
>   --ignore-missing-excel-columns, -m

Also, why did we convince ourselves that we need excel for each one of the importer commands? It seems superfluous to me

**Comment by PaprikaSteiger** [comment]
I removed the excel in the --ignore commands.

that --concept-name is shown as CONCEPT_NAME is default behavior of python. We can choose our own format, though we'd have to set this manually for every argument. So far, Gereon and I just overwrote default behavior for a few arguments...
Personally, I wouldn't change it, as the hypen is consistently rendered as an underscore.

**Comment by PaprikaSteiger** [comment]
@PaprikaSteiger Also adapt text of help

**Comment by nataliacp** [comment]
ok, now the underscore part is no longer relevant. 
I updated the description a bit. However, some of the allcaps are a bit terrible here. I don't know what this iterativity means. shouldn't all of them be as the --sheet argument? that they need to be repeated?
