### ISSUE TITLE
Is navigation any different in different operating systems???

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#212]
https://github.com/Anaphory/lexedata/blob/127ea4ccc8c3c52bb238faed9a69fd3ec88ee432/Manual/Manual.md?plain=1#L94

**Comment by PaprikaSteiger** [comment]
`cd` works pretty much on all operating systems. So far, the manual only mentions `cd`, so it should be fine.
According to Wikipedia all operating systems are: Unix, Unix-like, V, DOS, MSX-DOS, FlexOS, OS/2, TRIPOS, Windows, MPE/iX, Plan 9, Inferno, ReactOS, KolibriOS, SymbOS, DexOS

**Comment by Anaphory** [comment]
You also mention `ls`. The equivalent on Windows is `dir`. On my Linux, `dir` exists and is similar to `ls`. You might try if `dir` exists on Mac (whether your command line gives you similar output to `ls`) and then you can mention it instead of `ls`.

**Comment by nataliacp** [comment]
thank you! I will include both, because mac says I don't know what you are talking about with dir!
