### ISSUE TITLE
question on setting up git

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#213]
https://github.com/Anaphory/lexedata/blob/127ea4ccc8c3c52bb238faed9a69fd3ec88ee432/Manual/Manual.md?plain=1#L104
if somebody follows the tutorials say on github, like this one https://guides.github.com/introduction/git-handbook/, do they need to do something special to get git running on their computer?

**Comment by PaprikaSteiger** [comment]
Yes, one needs to install git. The guide can be found under `Quickstart` https://docs.github.com/en/get-started/quickstart/set-up-git
In general, I'd suggest to reference the `Quickstart`,  `Getting startet with git` (https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git) and the `Using Git` Guide.  
I think those are the minimal steps.
Although I don't know myself how the github app works, as I never use it.
Do we suggest using the app in our manual?

**Comment by nataliacp** [comment]
thanks! I will include these. We say the app is an option yes, but I haven't used it either. the way I wrote it is: you can use the app to interact with github, but you need the command line to interact with lexedata.
