### ISSUE TITLE
Manual talks about "concepts.csv" but code seems to stick with "parameters.csv" (the default)

### ISSUE THREAD

**Issue by xrotwang** [Anaphory/lexedata#222]
I came across the manual mentioning `concepts.csv` as typical part of a lexical CLDF dataset. This would be a deviation from the default name `parameters.csv` of the `ParameterTable` component. I didn't find `concepts.csv` anywhere in the code for `lexedata`, so I'd assume that datasets created with `lexedata` will also have `parameters.csv`, rather than `concepts.csv`.

**Comment by Anaphory** [comment]
Thanks for noticing!

The point where the non-default URL would at all appear in the code is https://github.com/Anaphory/lexedata/blob/master/src/lexedata/edit/add_table.py, which is a stub for a script we need to implement at some point.

In general, I assume consistent naming (“Parameter”) is more helpful than adopting the more transparent term where we can (“concepts.csv”) but keeping a confusing term elsewhere (“ParameterTable”), so I guess we'll change the manual.
