### ISSUE TITLE
we need to normalize usage descriptions

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#226]
I don't know if there is a standard way of doing things. This is what I wrote in the manual : 
`python -m lexedata.[package_name].[command_name] --[optional argument] [positional argument]`
the intention is to replace things in brackets. I see that you use this in some usage descriptions but in others the brackets are missing. Also for optional arguments, you use e.g. --column COLUMN, which I think is ok, since all optional arguments are explained below. 
opinions?

**Comment by Anaphory** [comment]
Traditionally (and that's the way Python composes it), there are square brackets around optional stuff. That is,

> usage: replace_id.py [-h] [--metadata METADATA] [--loglevel LOGLEVEL] [-q] [-v] [--merge] table original replacement

means “you may leave out the `--metadata METADATA`, but you have to give a table etc.”.

Also traditionally, the things in capital letters are replaced by your own appropriate text, but somehow I have never seen that done to positional arguments. Maybe I haven't looked properly. We can definitely make them all uppercase.
The way to describe it generically should then be

> python -m lexedata._package_._command_ [--_optional-argument_ VALUE] [--_switch_] POSITIONAL ARGUMENTS

or something like that – the _italics_ depend on the particular script, the CAPS on what one wants to do with that script.

**Comment by Anaphory** [comment]
We could easily do

> ```
> usage: replace_id.py [-h] [--metadata METADATA] [--loglevel LOGLEVEL] [-q] [-v] [--merge] TABLE ORIGINAL REPLACEMENT
> 
> Replace the ID of an object (eg. a language ID) in the wordlist
> 
> positional arguments:
>   TABLE                The table to apply the replacement to
>   ORIGINAL             Original ID to be replaced
>   REPLACEMENT          New ID of ORIGINAL
> 
> optional arguments:
>   -h, --help           show this help message and exit
>   --metadata METADATA  Path to the JSON metadata file describing the dataset (default: ./Wordlist-metadata.json)
>   --merge              When the replacement would lead to two IDs being merged, warn, but proceed.
> 
> Logging:
>   --loglevel LOGLEVEL
>   -q
>   -v
> ```

**Comment by nataliacp** [comment]
ok, great. I will update things in the manual as well.

**Comment by nataliacp** [comment]
Gereon help! how do you get italics within code? I tried googling and nothing works!

**Comment by Anaphory** [comment]
Markdown, I presume? The line above looks like this:

> `python -m lexedata._package_._command_ [--_optional-argument_ VALUE] [--_switch_] POSITIONAL ARGUMENTS`

Enclose some text in `_` on both ends, and Markdown will turn it into italics when it is translated to HTML, for example in the Github preview or in the Sphinx documentation renderer.
