### ISSUE TITLE
error message not working properly

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#227]
https://github.com/Anaphory/lexedata/blob/577154c0d154ce08da57a015a34348d5a0316557/src/lexedata/edit/replace_id.py#L30
the {args.replacement} and {args.table} are not working here. They stay as is in the error message.

**Comment by nataliacp** [comment]
this seems like I could fix it, but the arguments are indeed named replacement and table, so I don't get it.

**Comment by Anaphory** [comment]
A string that looks like `f"{variable}"` does the replacement, without `f`, so `"{variable}"` doesn't. I forgot that `f` at the start of line 30.

**Comment by Anaphory** [comment]
Actually, that was the general principle. Inside logging messages, the preference is something else, using % string formatting. Though I don't find the point in the documentation right now where it says so and gives the reasons.
