### ISSUE TITLE
merge IDs is too verbose

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#228]
ummm, it told me this (and did its job)
INFO:lexedata:Updating ids of Table(common_props={'dc:conformsTo': 'http://cldf.clld.org/v1.0/terms.rdf#ParameterTable', 'dc:extent': 859}, at_props={}, aboutUrl=None, datatype=None, default='', lang='und', null=[''], ordered=None, propertyUrl=None, required=None, separator=None, textDirection=None, valueUrl=None, dialect=None, notes=[], tableDirection='auto', tableSchema=Schema(common_props={}, at_props={}, aboutUrl=None, datatype=None, default='', lang='und', null=[''], ordered=None, propertyUrl=None, required=None, separator=None, textDirection=None, valueUrl=None, columns=[Column(common_props={}, at_props={}, aboutUrl=None, datatype=Datatype(common_props={}, at_props={}, base='string', format=None, length=None, minLength=None, maxLength=None, minimum=None, maximum=None, minInclusive=None, maxInclusive=None, minExclusive=None, maxExclusive=None), default='', lang='und', null=[''], ordered=None, propertyUrl=None, required=None, separator=None, textDirection=None, valueUrl=None, name='Ethnobio', suppressOutput=False, titles=None, virtual=False), Column(common_props={}, at_props={}, aboutUrl=None, datatype=Datatype(common_props={}, at_props={}, base='string', format=None, length=None, minLength=None, maxLength=None, minimum=None, maximum=None, minInclusive=None, maxInclusive=None, minExclusive=None, maxExclusive=None), default='', lang='und', null=[''], ordered=None, propertyUrl=URITemplate("http://cldf.clld.org/v1.0/terms.rdf#id"), required=None, separator=None, textDirection=None, valueUrl=None, name='CONCEPT', suppressOutput=False, titles=None, virtual=False), Column(common_props={}, at_props={}, aboutUrl=None, datatype=Datatype(common_props={}, at_props={}, base='string', format=None, length=None, minLength=None, maxLength=None, minimum=None, maximum=None, minInclusive=None, maxInclusive=None, minExclusive=None, maxExclusive=None), default='', lang='und', null=[''], ordered=None, propertyUrl=URITemplate("http://cldf.clld.org/v1.0/terms.rdf#name"), required=None, separator=None, textDirection=None, valueUrl=None, name='English', suppressOutput=False, titles=None, virtual=False), Column(common_props={}, at_props={}, aboutUrl=None, datatype=Datatype(common_props={}, at_props={}, base='string', format=None, length=None, minLength=None, maxLength=None, minimum=None, maximum=None, minInclusive=None, maxInclusive=None, minExclusive=None, maxExclusive=None), default='', lang='und', null=[''], ordered=None, propertyUrl=None, required=None, separator=None, textDirection=None, valueUrl=None, name='Spanish', suppressOutput=False, titles=None, virtual=False), Column(common_props={}, at_props={}, aboutUrl=None, datatype=Datatype(common_props={}, at_props={}, base='string', format=None, length=None, minLength=None, maxLength=None, minimum=None, maximum=None, minInclusive=None, maxInclusive=None, minExclusive=None, maxExclusive=None), default='', lang='und', null=[''], ordered=None, propertyUrl=None, required=None, separator=None, textDirection=None, valueUrl=None, name='Portuguese', suppressOutput=False, titles=None, virtual=False), Column(common_props={}, at_props={}, aboutUrl=None, datatype=Datatype(common_props={}, at_props={}, base='string', format=None, length=None, minLength=None, maxLength=None, minimum=None, maximum=None, minInclusive=None, maxInclusive=None, minExclusive=None, maxExclusive=None), default='', lang='und', null=[''], ordered=None, propertyUrl=URITemplate("http://cldf.clld.org/v1.0/terms.rdf#concepticonReference"), required=None, separator=None, textDirection=None, valueUrl=URITemplate("http://concepticon.clld.org/parameters/{Concepticon_ID}"), name='Concepticon_ID', suppressOutput=False, titles=None, virtual=False)], foreignKeys=[], primaryKey=['CONCEPT'], rowTitles=[]), transformations=[], url=<csvw.metadata.Link object at 0x7fdebd488970>, _fname=None, suppressOutput=False)
100%|██████████████████████████████████████████████████████████████████████████▉| 858/859 [00:00<00:00, 15434.39it/s]
INFO:lexedata:Writing concepts.csv back to file…
INFO:lexedata:Applying changed foreign key to columns {'CONCEPT'} in forms.csv…
INFO:lexedata:
40675it [00:04, 8650.05it/s]                                                                                         
INFO:lexedata:Writing forms.csv back to file…
INFO:lexedata:Applying changed foreign key to columns {'Core_Concept_ID'} in cognatesets.csv…
INFO:lexedata:
100%|██████████████████████████████████████████████████████████████████████▉| 21604/21605 [00:00<00:00, 28959.78it/s]
INFO:lexedata:Writing cognatesets.csv back to file…

**Comment by nataliacp** [comment]
ahem, now it doesn't warn at all about merging. I am not complaining, but this is what we say in the documentation. this is what I got: 
INFO:lexedata:Updating ids of concepts.csv
100%|██████████████████████████████████████████████████████████████████████████▉| 858/859 [00:00<00:00, 14084.76it/s]
INFO:lexedata:Writing concepts.csv back to file…
INFO:lexedata:Applying changed foreign key to columns {'CONCEPT'} in forms.csv…
INFO:lexedata:
40675it [00:04, 9146.08it/s]                                                                                         
INFO:lexedata:Writing forms.csv back to file…
INFO:lexedata:Applying changed foreign key to columns {'Core_Concept_ID'} in cognatesets.csv…
INFO:lexedata:
100%|██████████████████████████████████████████████████████████████████████▉| 21604/21605 [00:00<00:00, 29872.16it/s]
INFO:lexedata:Writing cognatesets.csv back to file…

**Comment by Anaphory** [comment]
Did you tell it to --merge? Then it assumed you know what you are doing, but I'll add an INFO.

**Comment by nataliacp** [comment]
yes, I did tell it to merge. the help says: warn but proceed. So, I am only saying it didn't warn me at all.

**Comment by Anaphory** [comment]
It's now INFO and proceed. Or will be, once we convince Travis' brother to let us merge.
