### ISSUE TITLE
help for add_concepticon is unclear

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#233]
I don't understand how to properly use gloss_language.

**Comment by nataliacp** [comment]
help is much better now, but where does somebody find these two letter codes? in concepticon somewhere?

**Comment by Anaphory** [comment]
They are just the normal [ISO 639-2](https://en.wikipedia.org/wiki/ISO_639-1) codes, although I don't know how we know which ones are actually implemented as glosses in Concepticon.

**Comment by Anaphory** [comment]
Found the list. https://github.com/concepticon/concepticon-data/tree/master/mappings
