### ISSUE TITLE
underscores for all optional arguments and switches

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#234]
I am currently substituting all hyphens in optional arguments and switches with underscores. I am doing this in the place where the help is described. Should I do it elsewhere as well? It seems that in the code they are already underscores.

**Comment by Anaphory** [comment]
But why?

--keep_forms looks so very strange to me. No other sensible program does it. Look for example at git:

> usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
>           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
>           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
>           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
>           [--super-prefix=<path>] [--config-env=<name>=<envvar>]
>           <command> [<args>]

I'd rather add a wrapper so that instead of `python -m lexedata.edit.add_metadata` you can write `lexedata edit add-metadata` and get consistency that way.

**Comment by nataliacp** [comment]
I am pretty sure this is what we had decided in that discussion about names. It is fine to change it, I just need to know! Right now, there seems to be a mix in there. 
I personally find it weird to have words separated by underscore in the command and by hyphen in the arguments, but this is coming from a naive perspective. If there is a tradition to do it this way, we can follow it and explain the weird tradition for people like me.

**Comment by Anaphory** [comment]
I think I have always maintained that the tradition is `-` and we should keep it wherever possible, it's just not possible inside a python variable name, and unfortunately our script names must be valid as python variable names.

I will think about writing that wrapper, so we can have the desired consistency, because normally `-` is also the thing inside command names.

**Comment by nataliacp** [comment]
ok, for the moment I will leave things as is till you decide

**Comment by Anaphory** [comment]
`-` everywhere where it is possible!

Where it is not possible yet, we'll work on making it possible in the future!

Hyphenminusdashes everywhere!

**Comment by PaprikaSteiger** [comment]
@Anaphory Mainly out of curiosity, so far I followed the convention (which I now have some doubts about whether I just made it up myself) `_` in script and variable names, but `-` for command line arguments.. Is this completely wrong?
Anyhow, I might be responsible for a big part of the mess...

**Comment by nataliacp** [comment]
no, this is exactly what we should be doing (we discussed it yesterday wtih Gereon). So, underscore for commands, hyphen for arguments and I am going to explain it in the manual. I will also change it if I see it differently anywhere.
