### ISSUE TITLE
help of add_metadata is not super clear

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#237]
right now the description says: Starting with a forms.csv, add metadata for all columns we know about.
What does exactly "we know about" mean?
Also, I find it confusing that this command has a metadata file as an optional argument. Is the idea that it is then updated?

**Comment by Anaphory** [comment]
Yes, the metadata file in this case is the one to *write*, it is not read. I have just changed it to catch the case of accidentally overwriting an existing metadata file.

The list of columns we “know about” is quite long:

 - All [default names of CLDF properties](https://cldf.clld.org/v1.0/terms.html#properties)
 - All [default names of CLDF reference properties](https://cldf.clld.org/v1.0/terms.html#reference-properties)
 - Plus a few more column names, some from LingPy, some from Lexedata, some from elsewhere: https://github.com/Anaphory/lexedata/blob/483124a84d701fccc7459b2aa3b94185c95ee3aa/src/lexedata/util/add_metadata.py#L12-L91

**Comment by nataliacp** [comment]
Can we have a better description? Something like. "Adds a metadata.json file automatically starting from a forms.csv file. Lexedata can guess metadata for a number of columns, including, but not limited to, all default CLDF properties (e.g. Language, Form) and CLDF reference properties (e.g. ParameterReference). We recommend that you check the metadata file created and adjust if necessary. "

**Comment by PaprikaSteiger** [comment]
@Anaphory Could you confirm or edit Natalia's suggestion? So I may change it
