### ISSUE TITLE
comments on add_metadata

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#238]
Lexedata created a json file from the Bantu test forms.csv and it looks fine! However, it tells me that it has added a column segments and a column source, but these are only added to the json file, and not to the forms.csv. Is this intended? If yes, then the INFO message is not clear. (I have stripped the sources from the Bantu test because they were not consistently marked in the original file and i didn't want to add it manually.)
I wanted to modify "from" to "for" in the info messages about segments and source, but I can find any of the info messages in the script file. Is this organized differently than the other scripts?

**Comment by Anaphory** [comment]
I think we have two conflicting design principles: “Don't change the existing forms.csv” and “Guess sensible metadata”. I guess we should scrap the first one and re-write the whole `forms.csv` to match the new metadata, so add empty columns?

**Comment by Anaphory** [comment]
And yes, the structure is different: We need to add metadata, or variants thereof, so often that the actual function is in util. Just changed it according to your suggestion:

https://github.com/Anaphory/lexedata/blob/6bc6ac61f79b66b926d4debeb0201d85c631721a/src/lexedata/util/add_metadata.py#L162

(“from” is in my lexicon for “expect”, so it wasn't a typo, just a style question.)
