### ISSUE TITLE
Breaking change in pycldf: KeyError → pycldf.dataset.SchemaError

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/lexedata#240]
In https://github.com/cldf/pycldf/issues/145 and https://github.com/cldf/pycldf/commit/4d6a5c4a750128cb1134a9ab77eb39c18a3b5640, pycldf has introduced a change that breaks our assumption everywhere that a missing table or column throws `KeyError`. So we need to go through and catch `pycldf.dataset.SchemaError` everywhere in addition to `KeyError` when the `try` is about a dataset table or column.

**Comment by xrotwang** [comment]
`SchemaError` is [a subclass of `KeyError`](https://github.com/cldf/pycldf/blob/f150f88d3c303a50698cb029d926ba9c1cdc0f53/src/pycldf/dataset.py#L37). So catching `KeyError` still works as well.

**Comment by xrotwang** [comment]
In fact, I left a couple of tests in place, see https://github.com/cldf/pycldf/blob/f150f88d3c303a50698cb029d926ba9c1cdc0f53/tests/test_dataset.py#L106 to make sure this assumption still holds.
