### ISSUE TITLE
how exactly do we update lexedata?

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#248]
https://github.com/Anaphory/lexedata/blob/f861698aa2fadb232dc7d50d12906d6ed6c35e45/docs/Manual.md?plain=1#L169
I am not sure if installing through pip or cloning the repository is the same thing. How does someone update?

**Comment by Anaphory** [comment]
I'll fix that. As quick explanation:

`pip install lexedata` installs the version from https://pypi.org/project/lexedata/, which needs to be updated manually by us, but does not install a new lexedata if there is already one installed.

`pip install --upgrade lexedata` upgrades Lexedata to the most recent version on pypi, same for all dependencies. (It does not update the *data* for the CLDF catalogs.)

It is possible to install lexedata directly from github, or from a local clone of the github repository, but I don't think that's relevant for the manual.
