### ISSUE TITLE
description of normalize_unicode needs tweaking

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#249]
ahem, it is a mixture of description, pseudocode and wondering. I am not sure how to fix it though! Is there something that the user needs to know about what is happening? I know next to nothing about encodings, apart that they terrify and frustrate me

**Comment by xrotwang** [comment]
Maybe a link would help, e.g. to this https://towardsdatascience.com/what-on-earth-is-unicode-normalization-56c005c55ad0

**Comment by nataliacp** [comment]
thanks! I definitely need to read this! (and I will add it to the manual as well)

**Comment by nataliacp** [comment]
reopening this, because the description in the help is still not good. There are some bits there that I would delete, but maybe you need to keep these notes somewhere?
