### ISSUE TITLE
concepticon connection script unexpected behavior

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#25]
after linking the MG list and also Vilacy's Tupian wordlist to concepticon, we have a couple of observations: 
- it seems that the matching is based on the concept IDs (is this MG specific because there are no english glosses?) I had to make Vilacy's glosses into an ID (without spaces or diacritics) in order for the script to work. Maybe the default option should be something different?
- it seems that two word concepts are not mapped. e.g. be born, be able to, be pregnant etc
- would it be possible to return candidate mappings when there is not a unique match? right now it seems too strict.

**Comment by Anaphory** [comment]
If you don't tell it to match based on gloss columns (`-l`), then it does assume your IDs are glosses.

Internally we use the concepticon API, so I can't easily mess with how mappings are done.

I'm not sure what the best way to return candidate mappings would be – the column we write back should be sensible and only contain one reference, not a choice of them.

**Comment by PaprikaSteiger** [comment]
@nataliacp @Anaphory I think this issue can be closed, right?
