### ISSUE TITLE
improve description of detect_cognates

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#257]
I think a bit more context is needed in the description of detect_cognates. Also, is it straight up the LingPy command, or there are differences? Finally, as I have never used LingPy myself, Gereon could you write up a paragraph in the manual for this?

**Comment by Anaphory** [comment]
This, and also `_cognate_code_language`, have been neglected so far and not considered a priority. I would keep them at that, and only look at them again after submission, so for a version 1.1 or similar.
