### ISSUE TITLE
add_central_concepts description more explicit?

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#259]
I think we should make the central concept description more explicit. I updated the help a bit. I saw a very nice description of what the algorithm does in the script file, but this is not anywhere visible. Should we put this in the manual? In the description? in both? what do you think?

**Comment by nataliacp** [comment]
also, it is not clear to me what happens if some concepts are linked to concepticon and others not. are they ignored?

**Comment by Anaphory** [comment]
I think that description (I assume you mean the docstring of `central concept`) would make some sense in the Manual.
Maybe the best way would be to make sure the function appears in the ‘internal API reference’ (which I think is not the case yet, but would be a reason to work on that) and then to link to it from that point in the manual?

If some or all concepts are not in CLICS, they are indeed ignored.

**Comment by nataliacp** [comment]
I am not sure what this internal API reference is and I don't completely follow all your linking magic. I am leaning towards putting a brief description in the manual at least for now.

**Comment by Anaphory** [comment]
Yes. Maybe I'll manage to implement what I mean soon, so I can show you.

**Comment by Anaphory** [comment]
I have worked it in. I'll tell you when we make it show up on readthedocs, so you can see what it generates.
