### ISSUE TITLE
error with importer.excel_interleaved

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#262]
I just tried importing the new giant Bantu dataset and I got this error. It is something with the script, rather than the file, right?
```INFO:lexedata:Parsing cells
  0%|                                                                                                                                                | 0/122 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/natalia/Documents/lexedata/src/lexedata/importer/excel_interleaved.py", line 150, in <module>
    for row in import_interleaved(sheet, logger=logger, ids=ids):
  File "/Users/natalia/Documents/lexedata/src/lexedata/importer/excel_interleaved.py", line 62, in import_interleaved
    while i < len(f):
TypeError: object of type 'int' has no len()```

**Comment by nataliacp** [comment]
deleting the extra header resolved the problem!

**Comment by nataliacp** [comment]
Running bantu again, I now get a helpful question if I have more than one header rows, but I cannot see any argument to put it in when I look at the command help.

**Comment by nataliacp** [comment]
I am on master, should I be elsewhere to expect this functionality?

**Comment by Anaphory** [comment]
No, we haven't implemented that because it raises a whole bunch of questions on how to interpret those additional header rows.
Can you give us the header of your data, so we can figure it out?

**Comment by nataliacp** [comment]
I would be more minimal and just add please make sure there is only one header row with language names or codes.

**Comment by nataliacp** [comment]
well, language names and codes!

**Comment by Anaphory** [comment]
Oh, right, so language metadata. That makes some sense, but yes, let's change the message to make clear we don't support that.

**Comment by Anaphory** [comment]
We ran into something related again.

 - [ ] If the last row, with cognate codes expected, is empty, warn the user that they might have mutliple headers.
