### ISSUE TITLE
comments on exporter.phylogenetics

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#263]
- [x] it says export a CLDF dataset (or similar). Is the or similar still true?
- [x] there is a warning (line 139) that shows that a lingpy format would be supported. Is this still true? Further down in line 175, another warning references an optional argument code_column, which no longer exists.
- [x] for the HalfPrimaryConcepts, you have a note that it cannot be guaranteed that there is a relevant concept for each cognate set. What happens in this case? Is there a warning?
- [x] line 446 there is a warning about a cognateset with a non-primary central concept. If I understand the description well, this cognateset will be ignored. This should be added to the warning.
- [ ] I imagine that another argument about primary concepts is going to be added to this command
- [x] crazy detail: I like CentralConcept and HalfPrimaryConcepts, can we make RootMeaning and RootPresence too? Or we make them with dashes like the optional arguments?
- [x] the statistics is the same as you get with the report script? Should we unify the name?

**Comment by Anaphory** [comment]
Metadatafree datasets are not supported any more, other formats even less, so I have removed that bracket.

**Comment by Anaphory** [comment]
The function that would support those (as well as Lingpy) still exists though, and there is no reason to make it dumber, so I left 139 and 175 as they were.
