### ISSUE TITLE
error in help?

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#268]
https://github.com/Anaphory/lexedata/blob/34657012e60dc9790b2f4aeaefa88e45fcf7328d/src/lexedata/importer/excel_long_format.py#L365

I am confused with the --sheet=Name, shouldn't one type --sheet NAME? Also, why type multiple times --sheet, when in other cases it is ok to do --match-form COLUMN COLUMN COLUMN?

**Comment by Anaphory** [comment]
Hm. It works both with and without the `=`, we should just use the one without.
I thought --sheet is short enough and it happens often enough that it makes sense to write it repeatedly.
--match-form on the other hand is quite long, and does tend to need multiple arguments.

So, how about I make `--match-form` also take one value each, but add `-m` as a shorthand?

**Comment by nataliacp** [comment]
ummmm I would think the opposite is easier, to make them both take multiple arguments. This is what happens with other things of this command if I remember well. 
By the way, I didn't know about the =!
