### ISSUE TITLE
help of report.judgements

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#279]
ummmm the help is not very helpful. It just says it checks that cognate judgements make sense! I will try to make more sense of it by running it and modify

**Comment by nataliacp** [comment]
based on the warnings I got on arawak, here is what I think it does:

- [ ] checks that the segments of the segment slice and the alignment are matching
- [ ] checks that the segment slice exists
- [ ] checks that the length of all alignments of a cognateset is the same
- [ ] other stuff?

**Comment by Anaphory** [comment]
- NA forms (Including "" for “source reports form as unknown” must not be in cognatesets)

**Comment by Anaphory** [comment]
It can also check theat the cognate coded segments are contiguous.
