### ISSUE TITLE
warnings of report.judgements

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#280]
I ran the report on arawak and got a shitload of warnings before there was an error. Here are some comments:

 I got tons of warnings of this kind and I don't understand them `WARNING:lexedata:In cognates.csv, row 6: Referenced segments in form resolve to m o t í, while alignment contains segments m o t í.
WARNING:lexedata:In cognates.csv, row 9: Referenced segments in form resolve to é d a, while alignment contains segments é d a.` why is it a problem if the referenced segments match the alignment? Or they don't match because of some unicode stupidity?

**Comment by Anaphory** [comment]
Unicode stupidity. I haven't figured out how to make that clearer in the warnings.

**Comment by nataliacp** [comment]
I checked it again now from fixes and there is an error with the arawak dataset, before warnings are spat out. 
```
INFO:lexedata:Caching table forms.csv
40675it [00:04, 9722.91it/s]                                                                                                                          
INFO:lexedata:Caching table forms.csv
40675it [00:04, 9951.48it/s]                                                                                                                          
Traceback (most recent call last):
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/natalia/Documents/lexedata/src/lexedata/report/judgements.py", line 248, in <module>
    if check_cognate_table(dataset, logger=logger, strict_concatenative=args.strict):
  File "/Users/natalia/Documents/lexedata/src/lexedata/report/judgements.py", line 216, in check_cognate_table
    if unicodedata.normalize(
ValueError: invalid normalization form
```
