### ISSUE TITLE
importer.excel_long_format requires metadata file

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/lexedata#295]
As @xrotwang pointed out:

To bootstrap a dataset it's unhandy that excel_long_format requires a metadata file, a LanguageTable, and a ParameterTable.
It's useful that it supports those if present, so if language or concept metadata are listed in separate columns from the forms' language references, they can be checked and imported. But the script should work without one.

**Comment by Anaphory** [comment]
This issue is thus part of the [JOSS review](openjournals/joss-reviews#4140)

**Comment by PaprikaSteiger** [comment]
If there is no metadata -> error (missing metadata, run add_metadata) "No cldf metadata found, if you have no metadata, export to csv from your excel file and run lexedata.edit.add_metadata"
If
