### ISSUE TITLE
Error in lexedata.edit.clean_forms

### ISSUE THREAD

**Issue by xrotwang** [Anaphory/lexedata#297]
Running `python -m lexedata.edit.clean_forms` results in
```
$ python -m lexedata.edit.clean_forms
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/robert_forkel/projects/lexedata/lexedata/src/lexedata/edit/clean_forms.py", line 250, in <module>
    forms = list(
  File "/home/robert_forkel/projects/lexedata/lexedata/src/lexedata/edit/clean_forms.py", line 127, in treat_brackets
    yield row | {
TypeError: unsupported operand type(s) for |: 'collections.OrderedDict' and 'dict'
```

**Comment by xrotwang** [comment]
It appears that `|` for `dict` was just added in Python 3.9, see https://www.python.org/dev/peps/pep-0584/

**Comment by xrotwang** [comment]
Given that test coverage for `lexedata` isn't particularly high (`lexedata.edit.clean_forms` isn't even imported in any test), I'd see three options:
- increase test coverage considerably
- only claim whatever the developers version of Python is as minimal supported version
- switch to python 3.8 for development.

Otherwise I don't think claiming support of python 3.8 would be justified.

**Comment by xrotwang** [comment]
I should note that I'd consider python 3.8 support somewhat important. I'm on Ubuntu 20.04 - which is still supported for another 2 years at least - and python 3.8 is the default python 3 installation :)

**Comment by xrotwang** [comment]
Oh, and I just read

> Python 3.9+ cannot be used on Microsoft Windows 7 or earlier versions. Last Windows 7 installable version is python 3.8 series.

which - if true - would also speak for maintaining py3.8 compatibility.

**Comment by Anaphory** [comment]
Yes, 3.8 support is the intention, and we are not at good at writing regression tests, otherwise that particular `|` operator would not have made it into release – we did see it being an issue in 3.8 but somehow it slipped back in. I'll drop my development version to 3.8 and see how I can get this replaced and tested.

**Comment by Anaphory** [comment]
There is a doctest, though, and 3.8 is in our Github workflow matrix, so I'm a bit confused why this was not picked up by the CI.

**Comment by xrotwang** [comment]
How are tests supposed to be run?

**Comment by xrotwang** [comment]
Just looked at tox.ini. That's quite a bit of machinery :)

**Comment by xrotwang** [comment]
So which doctest should run `clean_forms`?

**Comment by xrotwang** [comment]
Ok, this error **is** picked up when I run tox locally with py3.8.

**Comment by xrotwang** [comment]
From my experience, relying on GitHub actions alone for cross-form testing isn't ideal. So I typically run tox with a couple of pythons locally before release commits.

**Comment by Anaphory** [comment]
Well, the actual error you encountered is inside `treat_brackets`, which has its own doctest in its own docstring. Which is designed to encounter both the place where the `|` was and also check that the row is not mutated if there is a skip later. And the CI report https://github.com/Anaphory/lexedata/runs/5096896551?check_suite_focus=true#step:7:96 actually contains three “passing” dots for three doctests inside clean_forms.

Maybe I misconfigured the Github test matrix.

I'll keep the advice to test with multiple versions locally in mind for next release.

**Comment by xrotwang** [comment]
It seems you are not **really** running the tests on py3.8. Looking at the logs, it says
> uccessfully setup CPython (3.10.2)

**Comment by xrotwang** [comment]
You are also not running on "3.1" as the logs seems to say, but on 3.10 again. To specify 3.10, I needed to use `"3.10"`, i.e. a string, because `3.10` is read in yaml as `3.1`. So, something with your gh actions setup seems wrong.

**Comment by xrotwang** [comment]
FWIW, the matrix setup here works: https://github.com/glottolog/pyglottolog/blob/master/.github/workflows/python-package.yml

**Comment by Anaphory** [comment]
Yes, I was missing the `with:` clause. I had noticed the `3.1` but attributed it to the output instead of going to the root cause.
