### ISSUE TITLE
datetime error with importer.excel_interleaved

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#304]
Running Bantu again, I encountered a different error after a couple of warnings. 
```
INFO:lexedata:Parsing cells
  0%|                                                                                           | 0/122 [00:00<?, ?it/s]WARNING:lexedata:F84: Forms (kɛ̀bà ké léza̩là) did not match cognates (6, 1)
WARNING:lexedata:H100: Forms (mwur) did not match cognates (1, 2)
 10%|███████▉                                                                         | 12/122 [00:00<00:00, 321.14it/s]
Traceback (most recent call last):
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/natalia/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/natalia/Documents/lexedata/src/lexedata/importer/excel_interleaved.py", line 162, in <module>
    for row in import_interleaved(sheet, logger=logger, ids=ids):
  File "/Users/natalia/Documents/lexedata/src/lexedata/importer/excel_interleaved.py", line 96, in import_interleaved
    if isinstance(clean_cell_value(cogset), int):
  File "/Users/natalia/Documents/lexedata/src/lexedata/util/excel.py", line 28, in clean_cell_value
    v = unicodedata.normalize("NFC", (cell.value or "").strip())
AttributeError: 'datetime.datetime' object has no attribute 'strip'
```
I am suspecting that this is some format stupidity of the excel that has mistaken cognate codes for date and time. The excel was downloaded from google drive if this helps.

**Comment by Anaphory** [comment]
Excel's obnoxious tendency to assume that everything that even vaguely remotely looks like it might be a date is considered a date is a pain. Do you have cognate codes separated by `/` or `.` somewhere? We'll see what we can do to avoid this issue in general, but those would be my first guesses what to look for in your data.

**Comment by nataliacp** [comment]
I couldn't find any / or . associated with numbers. Any other ideas? Is there a way to understand from which row or column in the data this comes from?

**Comment by PaprikaSteiger** [comment]
@PaprikaSteiger  Throw error and proper warning

**Comment by Anaphory** [comment]
If the row is a forms row missing cognate codes, warn about the possibility that there was an even number of header rows which needs to be fixed. (That is, because we can accept arbitrary text as cognate codes, this is the only reliable way to notice something went wrong.)
