### ISSUE TITLE
Role of contributors

### ISSUE THREAD

**Issue by peterdekker** [Anaphory/lexedata#305]
(for review JOSS [#4140](https://github.com/openjournals/joss-reviews/issues/4140))

I see there is a contributor of a small amount of code in the repository, Walter Fuchs, who is not an author on the JOSS paper. Could you explain what was their role in the project? Thanks!

**Comment by Anaphory** [comment]
It's a pseudonym of @PaprikaSteiger

**Comment by peterdekker** [comment]
Okay, thanks!
