### ISSUE TITLE
JOSS paper: Explain choice for terminal tool

### ISSUE THREAD

**Issue by peterdekker** [Anaphory/lexedata#311]
https://github.com/openjournals/joss-reviews/issues/4140

To me, a quite surprising feature of this software package is that it is a terminal tool, not a library used in Python. I think it would be good to explain in the paper why this architecture has been chosen, which benefits does it have for the user?

**Comment by Anaphory** [comment]
By your comments, it looks like addressing both #301 and #308 will solve the confusion and explain the design, so we close this and address those.
