### ISSUE TITLE
Docs: Explain why using git is recommended

### ISSUE THREAD

**Issue by peterdekker** [Anaphory/lexedata#314]
https://github.com/openjournals/joss-reviews/issues/4140

From the docs, it becomes clear that it is highly recommended to use lexedata in conjunction with git. There is even a page explaining git to beginners. However, I never see the rationale mentioned, why users of lexedata have to use git (e.g. This makes it possible to save intermediate changes in your data/collaborate). I think this could be made more explicit in the documentation (e.g. in the tour or the main page), or possibly even in the paper.

**Comment by nataliacp** [comment]
I have added a sentence justifying git in the beginning of the tour and in the index file of the documentation. Given the length limit of the paper, i didn't find a very suitable place in there.

**Comment by Bisaloo** [comment]
For future reference, this was fixed in https://github.com/Anaphory/lexedata/commit/c4b9a9b28daa550fbb60f64247dd2e68dde4f6bd.
