### ISSUE TITLE
questions about NULL forms

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#318]
In the arawak polysemous report, I found: 
Unknown: Garifuna None {('LAGOTHRIX SP.', '10395'), ('BRADYPUS SP.', '9770')}
This happened because both of these concepts have empty forms. 

- [x] Do NULL forms used need to be declared somehow in the json file? I don't see something like this in the Arawak one
- [x] Assuming that they are indeed NULL forms, then they shouldn't be compared for the polysemous report, right?
- [x] If they are errors, shouldn't there be a warning that you have empty forms, what is going on?

**Comment by Anaphory** [comment]
You can set “required” for the form column to true or false, that declares whether they are permitted or not. We generally assume that the data set is consistent, even of not necessary appropriate for the task being executed. So the complaint “you have null forms, but you day forms are required” should come from CLFD validate.

I think it does indeed not make sense to have homophony with NULL forms.

**Comment by Anaphory** [comment]
NULL forms are skipped for homophones, so all should be fine:

https://github.com/Anaphory/lexedata/blob/16175c91c4aa78e8fb6846a886a6d2fed8a8fec9/src/lexedata/report/homophones.py#L51-L52
