### ISSUE TITLE
add option to add new concepts to ParameterTable with importer.excel_long_format

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#346]
I think this would be a good idea, no? Is there anything that prevents us from doing this?

**Comment by Anaphory** [comment]
Giving you a list of concepts that were added would be possible. Adding them to the ParameterTable would be as difficult as adding languages to the LanguageTable, which we decided to not do because we cannot.

**Comment by Anaphory** [comment]
Let's not add those automatically, but give a clean report that lists them all for inspection.

**Comment by nataliacp** [comment]
can it be not only for inspection, but in a way that allows someone to copy and paste in a table?

**Comment by Anaphory** [comment]
Hm, the only format I can imagine for that it every concept on a separate line, so you could paste it into a spreadsheet software showing when you edit `parameters.csv` – and that might be a lot of lines. Do you have better ideas?

**Comment by nataliacp** [comment]
no, this is exactly what I had in mind too

**Comment by nataliacp** [comment]
list-missing-concepts so it's not too long?
but summarize is fine too
