### ISSUE TITLE
can the add_cognate_table command read cognatesetReference with a separator?

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#361]
Kellen and I are trying to import sal data form the LingPy output. The cognateset ID has space as a separator, but it seems that the add_cognate_table cannot recognize it. We tried to define a separator in the json file, but again it doesn't work. Is this as intended? Can it be easily fixed?

**Comment by keyilan** [comment]
Where no separator is needed:

`9,9,['1498'],1:1,,`

When adding a separator, note the `"` around the array:

`10,10,"['13549', '13550']",1:5,,`
