### ISSUE TITLE
docs: adding `> output.txt` guidance for things like reporting

### ISSUE THREAD

**Issue by keyilan** [Anaphory/lexedata#363]
With large datasets the report function can result in a lot of terminal scrolling. This can be written instead to a file with `>`, which may be worth noting in the documentation for people who may not be familiar with that. Posting this as an issue on Natalia's suggestion.

**Comment by Anaphory** [comment]
This is worth a mention. If we say it, it should also be said that a lot of output we produce does not go to standard out, but to standard error, and a simple `>` will not be enough to redirect it. (I think for me a `2>` is enough, but I don't know how that translates to Mac and Windows.)

**Comment by nataliacp** [comment]
2> works for me on mac so it should be ok. I assume reports are > while the list of warnings should be 2>, right?

**Comment by Anaphory** [comment]
That is generally how it should work. There may be reports that are accidentally written to stderr or log messages written to stdout (unlikely), but those would be bugs that we'd need to fix.
