### ISSUE TITLE
importer.cognates messed up sources.bib

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#379]
I really can't understand what happened with this one. We started with a valid dataset (cldf validate sparkling clean) and tried to import a cognate spreadsheet. Between the time we had exported this cognate spreadsheet and the importation we had added a bunch of new languages to the dataset and new sources. All these changes were committed and the cldf again valid by the time we tried to import the cognate sets. The importation of the cognate sets seemingly worked fine, but the sources.bib was completely overwritten with a few sources that were of a weird format:
@misc{bibhandle, title = {bibhandle-repeated}}
the bibhandles were normal, but all other info was lost. We did git restore the sources.bib file and it all came back. Then the cldf validate was fine.
Any idea what the hell happened here???

**Comment by nataliacp** [comment]
This has now happened twice by running importer.cognates, so there is something happening, even though I can't see a connection!

**Comment by Anaphory** [comment]
The basic structure of that script is to read the dataset into a memory cache, drop its cognate data, read in the new cognate data, and write the cache back to the disk.

I suspect that thee cache claims to deal with bibliography data (it writes bib data, I assume), but doesn't actually read it properly. If that is it: The clean solution is likely to not re-write the whole dataset, but only the two Cognate(set)Tables
