### ISSUE TITLE
importer.cognates no longer has access to comment contents

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#380]
The importer correctly identifies that there is a comment associated with a cell in the cognate spreadsheet and puts a comment there when the cognate sets are exported. However, there is no content in the comment apart from #ERROR. I suspect that something has changed in xlsx and we no longer have access to the comment content.

**Comment by nataliacp** [comment]
We first saw this bug with Sara's computer which is a Windows machine. I just run a test with mine (mac) and still the comments do not appear correctly. I responded to one of the #ERROR comments (shown as if made by lexedata.exporter as expected) and now the comment thread has no content at all, while the commenter is shown as "====== ID#AAAAhkVUNP0...".

**Comment by Anaphory** [comment]
Ewwww. I hope this will require mostly an update of openpyxl (`pip install --update openpyxl`), but if this is something deeper or if openpyxl is not keeping up, this can be very difficult.
