### ISSUE TITLE
Create get_row_header function

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/lexedata#42]
This bunch

```
    row_header = []
    for (header,) in ws_test.iter_cols(
        min_row=1,
        max_row=1,
        max_col=len(dataset["CognatesetTable"].tableSchema.columns),
    ):
        column_name = header.value
        if column_name is None:
            column_name = dataset["CognatesetTable", "id"].name
        elif column_name == "CogSet":
            column_name = dataset["CognatesetTable", "id"].name
        try:
            column_name = dataset["CognatesetTable", column_name].name
        except KeyError:
            break
        row_header.append(column_name)
```

from the cognates importer and the corresponding loop tests should be a function.

**Comment by Anaphory** [comment]
@PaprikaSteiger had it as part of a big cognate importer class at some point. That was a bit too big, but the idea to wrap those bits of functionality into classes and functions was good.

**Comment by PaprikaSteiger** [comment]
@Anaphory The code in cognate importer is still wrapped in its own class. But not the functionality that creates the CogSet-header. Are you sure, you want that as a separate function?
It seems to me that it only serves for a specific case concerning the import of cognates.
Though, depending on what we come up with during our meeting tomorrow, me might want a create_header_from_excel function that can be used for different tables.

**Comment by Anaphory** [comment]
I'm not fussed about it being a function or a method of some class or whatever.
The guiding principle behind this issue is:
*If there is code duplication between a test and a CLI in a module, change that duplicated bit of code into something that can be shared and called from both the test and the CLI, so the test is closer to testing the CLI*.
Does that make sense, @PaprikaSteiger ? Can you do it?

**Comment by PaprikaSteiger** [comment]
@Anaphory I just reshaped the code now and put it into separate functions. Please have a look, there's some stuff that doesn't make that much sense for me. Like the unused separator in the create_header_function and the break. I left some TODOs in the code.
So how do you want it to be in the end?
