### ISSUE TITLE
Match function can match objects missing a property that we require.

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/lexedata#44]
https://github.com/Anaphory/lexedata/blob/6c278c18e80575355f61e226f128d67bdad17e99/src/lexedata/importer/fromexcel.py#L154-L157

Restructured match function potentially matches objects missing a property that we require.
If our cell parser was slightly dodgy, \<or> (with no phonemic transcription given) would match /and/. That sounds very bug-prone to me.
Did you ever encounter a KeyError ln line 157? Where would that come from, and can we complain about that error earlier? Because if there is a KeyError, something is fundamentally wrong with the dataset to be imported, and we should not sweep that error under the rug.

_Originally posted by @Anaphory in https://github.com/Anaphory/lexedata/pull/39#discussion_r520525658_

Yes, there were KeyErrors, the test script doesn't run with the old structure. I get:

```
>   all(match(properties[p], object[p]) for p in properties)]
E   KeyError: 'ID'
..\src\lexedata\importer\fromexcel.py:154: KeyError
```
Which I don't really understand.
_Originally posted by @PaprikaSteiger in https://github.com/Anaphory/lexedata/pull/39#discussion_r520525658_

**Comment by PaprikaSteiger** [comment]
@Anaphory I think this issue was just resolved by using `.get() `now:
```
[
    candidate
            for candidate, properties in self.cache[object.__table__].items()
            if all(
                match(properties.get(p), object.get(p)) for p in properties_for_match
            )
]
```

**Comment by Anaphory** [comment]
I think with that, this issue is resolved.
