### ISSUE TITLE
LOAN tag is converted to L;O;A;N after the loop

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#48]
I think this is due to the possibility of having multiple tags separated by ;. Somehow it thinks that LOAN is multiple tags. Maybe because it is in all caps?

**Comment by Anaphory** [comment]
Good find! It should do the same for any tag: Instead of taking every _semicolon-delimited_ part of the tag string as a separate tag, we forgot the split, so it's taking every part of the tag string, i.e. every individual letter.
