### ISSUE TITLE
Test with non-standard datasets

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/lexedata#63]
We need to test various sub-tools with valid, but non-standard datasets as well as with invalid, but human-comprehensible datasets, probably constructing tiny additional test datasets.
 - [x] lexedata.exporter.cognates expects that the CognatesetTable has a #parameterReference column. Test with a dataset without that.
 - [x] Test a metadata-free dataset, concepts are concepticon IDs, languages are glottocodes. How many functions can we get to work with that?
 - [x] Test with a dataset that has #cognatesetReference in the FormTable.
 - [x] Test both #parameterReference with a separator and without a separator.
 - [x] Test dataset with missing `sources.bib` and dataset with invalid `sources.bib`
 - [ ] Test with dataset where a inconsequential column ('ignored', let's say) is “required’ according to the metadata, but missing an entry.
 - [ ] Test with a ridiculously column-rich (including different data types – int/float/str, separators) and a ridiculously column-starved CognateTable (maybe even #id missing?), to see how they interact with Excel.

**Comment by PaprikaSteiger** [comment]
Gereon, I was planning to design another minimal dataset, not a minimal maweti set. I think I had the same in mind as you. Hope to find time for that after Christmas

**Comment by Anaphory** [comment]
Also test with invalid datasets

**Comment by Anaphory** [comment]
First one of these points has been addressed here:

https://github.com/Anaphory/lexedata/blob/fa3b51269d243b8bbc09b93be68bfdd0dee5ebbb/src/lexedata/exporter/cognates.py#L204-L209

**Comment by Anaphory** [comment]
Metadata-free datasets have the issue that only the columns with free metadata (ID, Language_ID, Parameter_ID, Form, Comment, Source) are added back on writing. That's not very handy.

**Comment by Anaphory** [comment]
I don't think having `#cognatesetReference`s in the FormTable is long-term sustainable, so I made a stub for converting such a dataset into the standard format with explicit CognateTable.
