### ISSUE TITLE
more info when importing new data

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#68]
It would be nice for the importer of the single wordlist to give a report including: 
how many new rows it read and what it did:
- X were new and imported
- Y were already existed and skipped
- Z were new concepts of existing forms and added
- A had problems and would correspond to warnings above

**Comment by nataliacp** [comment]
I thought that if the language is new, then it would say go add it. Right now it probably doesn't. I imported Apurinã (already existing, but apparently with a different character for the nasal vowel) and cldf validate complained that the key was not found.

**Comment by Anaphory** [comment]
> I thought that if the language is new, then it would say go add 
> it. Right now it probably doesn't. I imported Apurinã (already 
> existing, but apparently with a different character for the 
> nasal vowel) and cldf validate complained that the key was not 
> found. 

They are indeed not added. We don't have any information on them 
apart from the id (which might even be wrong, eg. someone keeping 
the sheet name 'Sheet 1') and typos like this happen far too easy, 
so not adding them and having CLDF validate complain sounded 
sensible for both typos and new additions.
What we *can* sensibly do is split the report you suggested by 
language (X forms were added, Y were given new concepts, etc.) and 
have that report include whether the language ID exists or not.

**Comment by nataliacp** [comment]
even better and more in line would be: I don't see this language ID, go add it, same as concepts

**Comment by Anaphory** [comment]
The reason I didn't suggest that is that you would get a million lines all for the same language. The report should be by language anyway (so you can see if you had one language behaving particularly badly in case you imported a mix), so that's also a good place to report on those missing languages, I thought.

**Comment by nataliacp** [comment]
I was thinking if it was possible to check the languages (at the level of tabs from the beginning). But I see your point if the languages are mixed up in a giant file.

**Comment by Anaphory** [comment]
It would be possible to throw that warning as early as it is encountered, I was just fearing it might vanish in the potential flood of forms with issues then.

**Comment by nataliacp** [comment]
could it be in the flood of warnings, but it stops the script until prompted? So, for example tab 3 has an unknown ID, it throws an error, says go fix it, and says press ignore to continue. It skips the entire tab and goes to the next. 
Now, if they are all mixed up in a giant file, it could stop when the first one is encountered and just skip all the next ones (or am I thinking too much like a human?)
another idea: it throws the flood of warnings and at the end they are summarized: X number of forms were ignored because the language ID "blabla" could not be found. go add it. Y number of forms were ignored because language ID "whatever" was not found, go add it

**Comment by Anaphory** [comment]
Hm. @nataliacp Prompting the user for something is a step I don't take lightly. A summarized warning somewhat like you suggest is what I would do. Let me try my hands at it and then discuss necessary changes with you.

**Comment by Anaphory** [comment]
Discussion result:

For each language, and then for the totals:
```
{Language Name} {"(new)" if new language else ""}:
 - {:d} new forms
 - {:d} forms existing already
 - {:d} new connections of existing forms to new concepts
 - {:d} forms skipped due to errors
 ```

**Comment by PaprikaSteiger** [comment]
I'm working on the report. Though there are some other issues with the single import. I think existing forms aren't treated correctly yet. I'll need to have a close look.
However, the report for now looks as follows:
```
| LanguageID   |   New forms |   Existing forms |   Skipped forms |   New concept reference |
|--------------+-------------+------------------+-----------------+-------------------------|
| (new)ache    |           3 |                0 |               6 |                       0 |
| Canamari     |           0 |                0 |               5 |                       0 |

```

**Comment by Anaphory** [comment]
I have changed the infrastructure a bit so that testing becomes easier, and written a first test using the `MockSingleExcelSheet` in `test_additional_importer.py`. This should help us test and debug whether (and why not) existing forms are treated correctly.

**Comment by Anaphory** [comment]
I added the same form for a new language twice, checking the report each time. The second time it doesn't just get the wrong number, it fails. @PaprikaSteiger can you check why 
```
>                       if new_concept not in db.cache[form_id][c_f_concept]:
E                       KeyError: 'new_language_one'

src/lexedata/importer/excelsinglewordlist.py:220: KeyError
============================== short test summary info ===============================
FAILED test/test_additional_importer.py::test_import_report[single_import_parameters0] - KeyError: 'new_language_one'
```
fix that and add some more tests for all the different report cases?

**Comment by Anaphory** [comment]
These tests seem to be running. The import of a form for a new language and of re-importing a form and of skipping a form seem to work, the test for adding a new concept to an existing form I'll just write in a moment.
