### ISSUE TITLE
adding new concepts to existing forms doesn't work

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#71]
I am not sure if this is a bug or it hasn't been implemented yet, but right now the single wordlist importer doesn't add new concepts to existing forms if it encounters them, but adds a new form altogether with the additional concept.
e.g. in Yawalapiti mapi was listed both as fur and body hair in the new data to import and it was imported twice (with distinct concepts). 
I know this will be caught by the homophony/polysemy script, but I just wanted to make sure it is intended behavior.

**Comment by Anaphory** [comment]
I *think* this may be because Arawak is currently not configured for polysemy, in that there is no `separator` in the metadata for #parameterRefernce. If I'm wrong, it's a bug indeedt.

**Comment by PaprikaSteiger** [comment]
I am unsure what to do about this issue. Currently the code does not add concepts, but only a new parameterReference to a form. I thought this change was done on purpose, as it has to be this way and only forms shall be imported.
Also new languages are not added to the dataset.

**Comment by nataliacp** [comment]
you are right Gereon, that there is no separator for parameterReference in the forms table. So, probably this is not a bug. Is it expected behavior for you, that when a form already exists with a different parameterReference, then it gets added again as a separate entry in forms.csv? If yes (and this is what I think), then we can test this functionality after adding polysemies in Arawak (a task for next year). I think we can close this, then.
