### ISSUE TITLE
enable NA forms

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#73]
Lokono has a bunch of them in the Arawak dataset. right now they are exported in singleton cognate sets with {  } forms.

**Comment by Anaphory** [comment]
That's it working as intended for now. We probably should have a complete list of expected Empty Form behaviour somewhere, though.

**Comment by PaprikaSteiger** [comment]
Maybe we can put this together with the still pending issue of `"..." `in the MG dataset?

**Comment by nataliacp** [comment]
"..." are in fact ? forms. NA forms are distinct, but they should be treated essentially the same, so I think it makes sense to deal with them together. ? means the form for this concept is unkown, while NA means this concept is not existing in this language (e.g. a species whose range does not overlap with the range of the language).

**Comment by Anaphory** [comment]
I hadn't got feedback on my earlier comment to CLDF yet, so now I've turned it into a separate issue there: https://github.com/cldf/cldf/issues/108

**Comment by Anaphory** [comment]
The current CLDF specs say

> ## Missing data
> Data creators often want to distinguish two kinds of missing data, in particular when the data is extracted from sources:
> 
> 1. data that is missing/unknown because it was never extracted from the source,
> 2. data that is indicated in the source as unknown.
> 
> The CSVW data model can be used to express this difference as follows: Case 1 can be modeled by not including the relevant data as row at all. Case 2 can be modeled using the null property of the relevant column specification as value in a data row.

This would suggest that our third case, where a meaning does not have a counterpart (and the counterpart is not just unknown) should be filled with a special value that is neither easy to confuse with a valid form nor with an actual null value.

So, "" and "NA" are out, but something like  *"/" or "–" or "-"* could be valid options for “Concept is known to not exist in the language”.

**Comment by Anaphory** [comment]
The general vote in the discussion seems to be in favour of **"-"**, so we'll go with that.

**Comment by Anaphory** [comment]
I have created a stubs file for all the NA tests I could think of in https://github.com/Anaphory/lexedata/blob/9c3a92447aa16d4a697f78095dacc9270dd95389/test/test_na_forms.py

Is there anything missing from it?

**Comment by PaprikaSteiger** [comment]
This is implemented for most of the scripts. Refer to test_na_forms.py to see the scripts that still lack an implementation.

**Comment by Anaphory** [comment]
- [ ] exporter/phylogenetics
   - [ ] Distinguish the case where `dataset[language][concept]` doesn't exist (no form given), and where it is empty (form given, but not associated with one of the cognatesets, so 0s for all cognatesets)
   - [ ] Make sure that "-" forms lead to an empty set in `dataset[language][concept]`.
 - [ ] extended_cldf_validate
   - [ ] Check that the "-" forms are in no cognateset
 - [ ] coverage_report
   - [ ] Report "-" forms as separate category

**Comment by Anaphory** [comment]
For exactly how we can treat missing forms in the report, let's see in practice what will be helpful.
