### ISSUE TITLE
segment slice with different separator?

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#74]
I don't know if we can, but the : separator for the segment slice is messed up by excel and google docs. They think it's time or something like that.

**Comment by Anaphory** [comment]
Ooof, not really. That colon is [deep in the CLDF specs](https://cldf.clld.org/v1.0/terms.rdf#segmentSlice), see the `"format": "\\d+(:\\d+)?"` for the #segmentSlice term.
