### ISSUE TITLE
help of enrich.segment_using_clts

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#75]
- the syntax of the command seems different from the others
- It mentions linking to concepticon, this is wrong I think
- it mentions wordlist, while it should be metadata file or something like that

**Comment by Anaphory** [comment]
@PaprikaSteiger Can you have a look at this one in particular when checking that all the scripts use the same flavor of switches for metadata (or forms.csv where possible without metadata) and other properties of the CLI?
