### ISSUE TITLE
Open usage issues

### ISSUE THREAD

**Issue by PaprikaSteiger** [Anaphory/lexedata#95]
Originally posted in  ##64
- excelsinglewordlist.py: (...) I am not sure here if this script should directly make the singleton cognatesets or if the exporter should as we have it now. The reason I am thinking of this is because we want cldf to be valid after a script. So, do we allow forms that are not in cognate sets (within the "policed" concepts) to go without a warning?
- guess_concepticon.py: (...) I would also like to add here that based on my concept linking with MG, I think for the verification to work with minimal looking up of concepticon, it needs to pull in three things: the concept set ID, the name and the definition. A follow up we could think about would be an option to update name and definition based on the ID for updating the dataset (I don't even know if such updates are common enough, Gereon?)
- segments_using_clts.py: I am not sure that we want an update here by default. I am imagining a case where you import a bunch of stuff at different times, then you segment so you can export, and then everything becomes "segmented". Assuming the segmenter is solid, I think segmentation is largely hidden from the user and should remain so. I think I would just add a thing in the manual saying if you have weird stuff in your unified forms, then check that the segmentation is correct but that's all. Or maybe this one should be additive and not replace a previous status. 
**Currently, no other scripts calls segment_using_clts.py. When should another script check if a Segments column exists and possibly create one?**

**Comment by Anaphory** [comment]
- CLDF validate doesn't mind concepts not being in cognatesets. I don't think the importer should mess with things that don't actually interest it, who says there even are cognate sets yet?
 - I don't know what the second point is.
 - 1. Automatic Cognate Detection assumes that you have segments. So, Automatic Cognate Detection should fail if there are no segments and suggest you run the segmenter. 2. The cognateset exporter currently assumes there are segments and segment slices that refer to them. This could maybe become optional, or it should also fail with the same help. 3. In the future, the Edictor export as well as a sensible alignment script or something for sound correspondences will probably need segments.

**Comment by Anaphory** [comment]
- …
- Natalia's suggestion is to add Names (and Definitions) from Concepticon to the cognates table – and it would make sense to implement this as a separate program, so you can run it in case Concepticon changes.
- …

**Comment by nataliacp** [comment]
not the to cognates table, to the concepts table!

**Comment by Anaphory** [comment]
That's what I meant, sorry!

**Comment by PaprikaSteiger** [comment]
Let me try to resume: 
- Create new script that adds columns Concepticon_Name and Concepticon_Definition to a /#CognateTable of a given dataset. 
I guess the script should use the Concepticon_ID in the \#ParameterTable via the link with the \#FormTable

**Comment by nataliacp** [comment]
it would be to the Concept table (i.e. parameter table), Melvin, so you
only need to use the parameter table and nothing else.

**Comment by PaprikaSteiger** [comment]
Thanks, Natalia. Just adapted it.

**Comment by Anaphory** [comment]
@nataliacp @PaprikaSteiger Is there anything left to do for this issue?
