### ISSUE TITLE
comments accumulate signatures -lexedata.exporter

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#97]
Due to the handling of comments by xlsx (it adds as a signature the name of the person who wrote the comment), comments over multiple loops accumulate signatures. 
examples ALOUATTA SP.9 in Garifuna
ANACARDIUM SP.21 in Achagua

**Comment by PaprikaSteiger** [comment]
I think you can delete the author of a comment in excel. At least it works for me. When you open the comment and write in it, just delete the author.
Otherwise they accumulate, yes.
